"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import queryClient from "./utils/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import { AlertProvider } from "./context/AlertContext";
import { AppProvider } from "./context/AppContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Monster Havoc",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <AppProvider>
          <QueryClientProvider client={queryClient}>
            <AlertProvider>{children}</AlertProvider>
          </QueryClientProvider>
        </AppProvider>
      </body>
    </html>
  );
}
